### ISSUE TITLE
F-Droid build fails `./make.sh: Syntax error: "(" unexpected`

### ISSUE THREAD

**Issue by licaon-kter** [supertuxkart/stk-code#4408]
Trying to build 1.2, full error
```
Building APK
./make.sh: 535: ./make.sh: Syntax error: "(" unexpected
```
...but line number might not correlate since we remove some stuff, see this diff:
```
--- a/android/make.sh
+++ b/android/make.sh
@@ -218,29 +218,6 @@
     exit
 fi
 
-# Check if we have key for signing in release build
-if [ "$GRADLE_BUILD_TYPE" = "assembleRelease" ]; then
-    if [ -z "$STK_KEYSTORE" ]; then
-        echo "Error: STK_KEYSTORE variable is empty."
-        exit
-    fi
-
-    if [ ! -f "$STK_KEYSTORE" ]; then
-        echo "Error: Couldn't find $STK_KEYSTORE file."
-        exit
-    fi
-
-    if [ -z "$STK_STOREPASS" ]; then
-        echo "Error: STK_STOREPASS variable is empty"
-        exit
-    fi
-
-    if [ -z "$STK_ALIAS" ]; then
-        echo "Error: STK_ALIAS variable is empty."
-        exit
-    fi
-fi
-
 # Find newest build-tools version
 if [ -z "$BUILD_TOOLS_VER" ]; then
     BUILD_TOOLS_DIRS=`ls -1 "$SDK_PATH/build-tools" | sort -V -r`
@@ -702,19 +679,13 @@
 fi
 
 export ANDROID_HOME="$SDK_PATH"
-./gradlew -Pcompile_sdk_version=$COMPILE_SDK_VERSION \
+gradle -Pcompile_sdk_version=$COMPILE_SDK_VERSION \
           -Pbuild_tools_ver="$BUILD_TOOLS_VER"       \
-          -Pstorepass="$STK_STOREPASS"               \
-          -Pkeystore="$STK_KEYSTORE"                 \
-          -Palias="$STK_ALIAS"                       \
           $GRADLE_BUILD_TYPE
 
 if [ "$GRADLE_BUILD_TYPE" = "assembleRelease" ]; then
-./gradlew -Pcompile_sdk_version=$COMPILE_SDK_VERSION \
+gradle -Pcompile_sdk_version=$COMPILE_SDK_VERSION \
           -Pbuild_tools_ver="$BUILD_TOOLS_VER"       \
-          -Pstorepass="$STK_STOREPASS"               \
-          -Pkeystore="$STK_KEYSTORE"                 \
-          -Palias="$STK_ALIAS"                       \
           "bundleRelease"
 fi
```
Actual line: https://github.com/supertuxkart/stk-code/blob/1.2/android/make.sh#L558

Full log: [org.supertuxkart.stk_145.log.gz](https://github.com/supertuxkart/stk-code/files/5428235/org.supertuxkart.stk_145.log.gz)

Modified metadata for reference:
```
  - versionName: '1.2'
    versionCode: 145
    commit: '1.2'
    subdir: android
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y imagemagick pngquant vorbis-tools
    output: build/outputs/apk/release/android-release-unsigned.apk
    srclibs:
      - supertuxkartdeps@5b135b51bdddc3ce91af70dd2add7fb8a5ece964
    prebuild:
      - sed -i -e 's#./gradlew#gradle#' -e '/Check\ if\ we\ have\ key/,+22d' -e '/Pstorepass/,+2d' make.sh
      - wget https://github.com/supertuxkart/stk-assets-mobile/releases/download/$$VERSION$$/stk-assets-lq.zip
      - echo '9d5a921efa63ef27756af171900fa73566c262c83358fad2f1f337b85f1b54bc  stk-assets-lq.zip'
        | sha256sum -c -
      - unzip stk-assets-lq.zip -d stk-assets
      - sed -i -e 's#../../stk-assets#stk-assets#' generate_assets.sh
      - tar -C '../lib' -xf $$supertuxkartdeps$$/dependencies-android-1.2.tar.xz
    scanignore:
      - android/stk-assets/textures/
    scandelete:
      - android/stk-assets-lq.zip
      - lib/curl/tests
      - lib/freetype/docs/reference/sitemap.xml.gz
      - lib/harfbuzz/test/
      - lib/sdl2/Xcode/SDL/pkg-support/resources/SDL_DS_Store
      - tools/windows_installer
    build:
      - export BUILD_TYPE=release
      - export SDK_PATH=$$SDK$$
      - export NDK_PATH=$$NDK$$
      - export PROJECT_VERSION=$$VERSION$$
      - export PROJECT_CODE=$$VERCODE$$
      - export DECREASE_QUALITY=0
      - export CONVERT_TO_JPG=0
      - ./generate_assets.sh
      - ./make.sh
    ndk: r20b
```
