### ISSUE TITLE
1.5-beta1 - Android - can't build, shaderc is gone

### ISSUE THREAD

**Issue by licaon-kter** [supertuxkart/stk-code#5391]
### Description

https://github.com/supertuxkart/stk-code/blob/1.5-beta1/android/make_deps.sh#L287-L308

is this needed or not?

### Steps to reproduce

-

### Configuration

-

### Error message

```
[Paste error message here]
```

### Log File (stdout.log)

```
[Paste contents of stdout.log here]
```

### Input Configuration (input.xml)

```
[Paste contents of input.xml here]
```

**Comment by BcfWor** [comment]
Test

**Comment by licaon-kter** [comment]
HEAD builds fine at least 0f6dbc741a455bb363427d5d3b3cd1637b8f13b9 does, with HEAD https://github.com/supertuxkart/dependencies/commit/ed73ce6c0f2a14ed1c54c38ef4d28a074b837b49 deps

now, for some reason a file was not created in the assets so I need to do
```
...
      - ./generate_assets.sh
      - touch assets/data/supertuxkart.1.5-beta1
      - sed -i -e '\!cacert.pem!adata/supertuxkart.1.5-beta1' assets/files.txt
...
```
is this expected?


how far is 1.5-beta2? 😄 


full recipe for reference
```
  - versionName: '1.5-beta1'
    versionCode: 319
    commit: 0f6dbc741a455bb363427d5d3b3cd1637b8f13b9
    subdir: android
    sudo:
      - apt-get update
      - apt-get install -y advancecomp autoconf automake bsdextrautils cmake imagemagick
        libjpeg-progs libogg-dev make optipng pngquant vorbis-tools xz-utils yasm file
    output: build/outputs/apk/release/android-release-unsigned.apk
    prebuild:
      - sed -i -e 's#./gradlew#gradle#' -e '/Check\ if\ we\ have\ key/,+25d' -e '/ANDROID_HOME/,+14d'
        -e 's/bundleRelease/assembleRelease/' make.sh
      - sed -i -e '/keystore/,+3d' build.gradle
      - sed -i -e 's#../../stk-assets#stk-assets#' generate_assets.sh
      - curl -Lo stk-assets-full.zip https://github.com/supertuxkart/stk-assets-mobile/releases/download/$$VERSION$$/stk-assets-full.zip
      - echo '25a92330b1fe049c8f1ae59f92966e580b366571f4a14a0b30fec7a2be275209  stk-assets-full.zip'
        | sha256sum -c -
      - unzip stk-assets-full.zip -d stk-assets
      - git clone https://github.com/supertuxkart/dependencies
      - cd dependencies
      - git submodule update --init --recursive
      - mv src/* ../../lib/
    scandelete:
      - android/stk-assets-full.zip
      - lib/curl/tests
      - lib/harfbuzz/test
      - lib/mbedtls/tests
      - lib/mbedtls/programs/fuzz
      - lib/sdl2/Xcode/SDL/pkg-support/resources/SDL_DS_Store
    build:
      - export BUILD_TYPE=release
      - export COMPILE_ARCH=all
      - export SDK_PATH=$$SDK$$
      - export NDK_PATH=$$SDK$$/ndk
      - export PROJECT_VERSION=$$VERSION$$
      - export PROJECT_CODE=$$VERCODE$$
      - ./generate_assets.sh
      - touch assets/data/supertuxkart.1.5-beta1
      - sed -i -e '\!cacert.pem!adata/supertuxkart.1.5-beta1' assets/files.txt
      - ./make_deps.sh
      - bash ./make.sh
    ndk: r23b
```
